# Generated by Django 6.1 on 2026-08-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('marca', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('autonomia_minutos', models.IntegerField(help_text='Tempo de voo em minutos')),
                ('alcance_km', models.FloatField(help_text='Alcance máximo em quilômetros')),
                ('estoque', models.PositiveIntegerField(default=0)),
                ('imagem', models.ImageField(upload_to='drones/')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
